APP_SRCS += lv_arc.c
APP_SRCS += lv_bar.c
APP_SRCS += lv_cb.c
APP_SRCS += lv_cpicker.c
APP_SRCS += lv_ddlist.c
APP_SRCS += lv_kb.c
APP_SRCS += lv_line.c
APP_SRCS += lv_mbox.c
APP_SRCS += lv_preload.c
APP_SRCS += lv_roller.c
APP_SRCS += lv_table.c
APP_SRCS += lv_tabview.c
APP_SRCS += lv_tileview.c
APP_SRCS += lv_btn.c
APP_SRCS += lv_calendar.c
APP_SRCS += lv_chart.c
APP_SRCS += lv_canvas.c
APP_SRCS += lv_gauge.c
APP_SRCS += lv_label.c
APP_SRCS += lv_list.c
APP_SRCS += lv_slider.c
APP_SRCS += lv_ta.c
APP_SRCS += lv_spinbox.c
APP_SRCS += lv_btnm.c
APP_SRCS += lv_cont.c
APP_SRCS += lv_img.c
APP_SRCS += lv_imgbtn.c
APP_SRCS += lv_led.c
APP_SRCS += lv_lmeter.c
APP_SRCS += lv_page.c
APP_SRCS += lv_sw.c
APP_SRCS += lv_win.c

# DEPPATH += --dep-path $(LVGL_DIR)/lvgl/src/lv_objx
# VPATH += :$(LVGL_DIR)/lvgl/src/lv_objx

# CFLAGS += "-I$(LVGL_DIR)/lvgl/src/lv_objx"
